name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag deweiliu/indexing:latest
        docker login --username deweiliu --password ${{ secrets.DockerHub }}
        docker push deweiliu/indexing:latest
        docker logout